# Generated by Django 5.0.6 on 2024-07-01 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TestimonialsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('subheader', models.CharField(max_length=100)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials_page', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('include', models.BooleanField(default=True)),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_items', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=100)),
                ('include', models.BooleanField(default=True)),
                ('items', models.ManyToManyField(to='portfolios.navigationitem')),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='navigation', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=100)),
                ('firstButtonText', models.CharField(max_length=50)),
                ('firstButtonLink', models.CharField(max_length=100)),
                ('secondButtonText', models.CharField(max_length=50)),
                ('secondButtonLink', models.CharField(max_length=100)),
                ('blogPreview', models.BooleanField(default=True)),
                ('includeBlogButton', models.BooleanField(default=True)),
                ('blogButtonText', models.CharField(max_length=50)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_page', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iconSpacingY', models.IntegerField()),
                ('iconSpacingX', models.IntegerField()),
                ('iconSize', models.IntegerField()),
                ('iconColor', models.CharField(max_length=7)),
                ('include', models.BooleanField(default=True)),
                ('text', models.CharField(max_length=255)),
                ('github', models.BooleanField(default=False)),
                ('githubLink', models.URLField(blank=True, null=True)),
                ('linkedin', models.BooleanField(default=True)),
                ('linkedinLink', models.URLField()),
                ('twitter', models.BooleanField(default=False)),
                ('twitterLink', models.URLField(blank=True, null=True)),
                ('facebook', models.BooleanField(default=False)),
                ('facebookLink', models.URLField(blank=True, null=True)),
                ('resume', models.BooleanField(default=True)),
                ('resumeLink', models.URLField()),
                ('email', models.BooleanField(default=True)),
                ('emailAddress', models.EmailField(max_length=254)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='FAQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('website', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_questions', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='FAQPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(to='portfolios.faqquestion')),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faq_page', to='portfolios.website')),
            ],
        ),
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('subheader', models.CharField(max_length=100)),
                ('firstNameLabel', models.CharField(max_length=50)),
                ('firstNamePlaceholder', models.CharField(max_length=50)),
                ('lastNameLabel', models.CharField(max_length=50)),
                ('lastNamePlaceholder', models.CharField(max_length=50)),
                ('emailLabel', models.CharField(max_length=50)),
                ('emailPlaceholder', models.CharField(max_length=50)),
                ('messageLabel', models.CharField(max_length=50)),
                ('messagePlaceholder', models.CharField(max_length=50)),
                ('subscribeLabel', models.CharField(max_length=100)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_page', to='portfolios.website')),
            ],
        ),
    ]
