# Generated by Django 5.0.6 on 2024-07-01 00:37

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_navigationitem_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faqpage',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='faqpage',
            name='website',
        ),
        migrations.RemoveField(
            model_name='faqquestion',
            name='website',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='website',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='website',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='items',
        ),
        migrations.RemoveField(
            model_name='navigation',
            name='website',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='section',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='website',
        ),
        migrations.RemoveField(
            model_name='testimonialspage',
            name='website',
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=True)),
                ('header', models.CharField(blank=True, default='FAQ', max_length=300, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350, null=True)),
                ('answer', ckeditor.fields.RichTextField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='portfolios.faqsection')),
            ],
        ),
        migrations.DeleteModel(
            name='ContactPage',
        ),
        migrations.DeleteModel(
            name='FAQPage',
        ),
        migrations.DeleteModel(
            name='FAQQuestion',
        ),
        migrations.DeleteModel(
            name='Footer',
        ),
        migrations.DeleteModel(
            name='HomePage',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='NavigationItem',
        ),
        migrations.DeleteModel(
            name='TestimonialsPage',
        ),
        migrations.DeleteModel(
            name='Website',
        ),
    ]
