# Generated by Django 5.0.6 on 2024-07-01 01:30

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0003_remove_faqpage_questions_remove_faqpage_website_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=True)),
                ('button', models.CharField(blank=True, default='View all blogs', max_length=300, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blogs/')),
                ('title', models.CharField(max_length=300)),
                ('date', models.DateField(auto_now_add=True)),
                ('text', ckeditor.fields.RichTextField(null=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='portfolios.blogsection')),
            ],
        ),
    ]
