# Generated by Django 5.0.6 on 2024-07-01 02:00

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0004_blogsection_blog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestimonialSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('include', models.BooleanField(default=True)),
                ('header', models.CharField(blank=True, default='View all blogs', max_length=300, null=True)),
                ('subheader', models.CharField(blank=True, default='View all blogs', max_length=300, null=True)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='testimonials/profile/')),
                ('company_image', models.ImageField(blank=True, null=True, upload_to='testimonials/company/')),
                ('testimonial_giver_name', models.CharField(max_length=300)),
                ('testimonial_giver_position', models.CharField(max_length=300)),
                ('testimonial_text', ckeditor.fields.RichTextField(null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolios.testimonialsection')),
            ],
        ),
    ]
