# Generated by Django 5.0.6 on 2024-07-02 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0005_testimonialsection_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='company_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
