# Generated by Django 5.0.6 on 2024-07-04 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0006_alter_testimonial_company_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=300, unique=True),
        ),
    ]
