# Generated by Django 5.0.6 on 2024-07-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0007_testimonial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='slug',
            field=models.SlugField(blank=True, max_length=300),
        ),
    ]
